import jsPDF from "jspdf";

export const generateReceipt = (
  transaction: any
) => {
  const doc = new jsPDF();

  // Header Background
  doc.setFillColor(15, 45, 82);
  doc.rect(0, 0, 210, 50, "F");

  // Logo/Title
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.text(
    "PayFlow",
    105,
    18,
    { align: "center" }
  );

  doc.setFontSize(16);
  doc.text(
    "Transaction Receipt",
    105,
    30,
    { align: "center" }
  );

  // Amount Section
  doc.setTextColor(0, 0, 0);

  doc.setFontSize(12);
  doc.text(
    "Amount",
    105,
    70,
    { align: "center" }
  );

  doc.setFontSize(28);
  doc.setTextColor(15, 45, 82);

  doc.text(
    `₦${Number(
      transaction.amount
    ).toLocaleString()}`,
    105,
    85,
    { align: "center" }
  );

  // Divider
  doc.setDrawColor(220);
  doc.line(20, 95, 190, 95);

  // Details
  doc.setFontSize(12);
  doc.setTextColor(80);

  let y = 110;

  const row = (
    label: string,
    value: string
  ) => {
    doc.text(label, 20, y);

    doc.text(
      value,
      190,
      y,
      { align: "right" }
    );

    y += 15;
  };

  row(
    "Reference",
    transaction.reference
  );

  row(
    "Description",
    transaction.description ||
      "Transfer"
  );

  row(
    "Status",
    transaction.status
  );

  row(
    "Type",
    transaction.type
  );

  row(
    "Date",
    new Date(
      transaction.created_at
    ).toLocaleString()
  );

  // Footer
  doc.setFillColor(245, 245, 245);

  doc.rect(
    0,
    260,
    210,
    37,
    "F"
  );

  doc.setFontSize(10);

  doc.text(
    "Generated by PayFlow",
    105,
    280,
    { align: "center" }
  );

  doc.save(
    `PayFlow-${transaction.reference}.pdf`
  );
};